import Header from "@/components/Header/Header";
import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Footer from "@/components/Header/Footer";
import { NumberProvider } from "@/context/nav.context";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Esx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap'
        />
      </head>
      <body className={`  relative   min-h-[101vh]   min-w-[100vw] p-0 m-0`}>
        <NumberProvider>
          <Header />
          {children}
          <Footer />
        </NumberProvider>
      </body>
    </html>
  );
}
